### ISSUE TITLE
undefined err in decryptor.rb

### ISSUE THREAD

**Issue by amorcomb** [maxlinc/puppet-decrypt#5]
Installed puppet-decrypt on a new node and encountered a new error:

$ puppet crypt encrypt foo 
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /etc/puppet/modules/puppet_decrypt/lib/puppet-decrypt/decryptor.rb:5: undefined (?...) sequence: /^ENC:?(?<key>\w_)[(?<value>._)]$/ (SyntaxError)

5: ENCRYPTED_PATTERN = /^ENC:?(?<key>\w_)[(?<value>._)]$/

Anything change recently?

**Comment by maxlinc** [comment]
I see from the path you're still using ruby 1.8.  Let me echo the statements of the Fog developers:

> ## Ruby 1.8.7
> 
> The maintainers of this project, in concert with the maintainers of Ruby,
> **strongly** recommend using the latest patchlevel of Ruby 1.9.2 or later.
> As of July 1, 2013, Ruby 1.8.7 is no longer officially maintained.
> This means fixes will no longer be provided, even for known security
> vulnerabilities.
> 
> [retired]: http://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/

I tried to prevent installation on Ruby 1.8.7 via the Gemspec.  I will investigate why it didn't work.

**Comment by amorcomb** [comment]
Don't spin your wheels on it. I found a workaround. I understand the dependency on 1.9. But I'll reiterate as well, AWS is a 300lb gorilla and as long as they continue to ship 1.8.7 with their Linux images, it won't go away.
